
from re import compile as regex


foi = {
  "*": [".*escription$","^(.+/)?[Tt]ext$","^(.+/)?[Dd]ialog/[^/]+/[^/]+/.*[0-9]+$",
    "^(.+/)?(sub)?[tT]itle(/value)?$", "^(.+/)+caption$", "^(.+/)?label$",
    "^(.+/)?message$", "^(.+/)?dialog$", "^.+Name/value$", "^.*friendlyName$", ".*senderName$",
    ".*destinations/.+[Nn]ame$", ".+[lL]abel[a-zA-Z]*/(value|name)$",
    "bookmarkName"],
  ".object": ["^chatOptions/.+$",],
  ".codex": ["contentPages/[0-9]+$"],
  ".matherial": [],
  ".config": ["^(.*/)?(?!generatedParameters)[a-zA-Z]+/displayName$",
    "^(.+/)?lbl[a-zA-Z]+/value$", "^labels/.+$", "^otherDeed/.+$", "^.*Format$",
    "^enclosedArea/.+$", "^tagCriteria/.+$", "^hail/.+$", "^converse/.+$",
    "^follow/.+$", "^flee/.+$", "^encorage/.+$", "^severe/.+$", "^accuse/.+$",
    "^tout/.+$", "^rent/.+$", "^alert/.+$", "^welcome/.+$", "^beacon/.+$",
    "^safe/.+$", "^helpme/.+$", "^final/.+$", "^.+Text(/value)?$",
    "^gui.+/value$", "^paneLayout/.+/value$", "areYouSure/value$",
    "^blueprintUnlock$", "^blueprintAlreadyKnown$",
    "^rotTimeDescriptions/.+/1$", "^[a-zA-Z]*[mM]essages/[a-zA-Z]+$",
    ".+[mM]essage$", "^.*(hint|regex|([a-zA-Z]*(Caption|[Tt]itle)))$",
    "^defaultPetNameLabel$", ".*descriptions/[0-9]+$", "^(un)?trackLabel$",
     "^modeTypeTextAndColor/[0-9]+/[0-9]+$"],
  "themes.config":["^[0-9]+/1/[0-9]+/(0|(1/)?name)$"],
  "placestation.config":["^.*Text/[^/]+$"],
  "dungeonitems.config":["^[0-9]+/1/[0-9]+/(0|(1/)?name)$"],
  "threats.config":["^[0-9]+/1/[0-9]+/(0|(1/)?name)$"],
  "weapon.config":["^[0-9]+/1/[0-9]+/(0|(1/)?name)$"],
  "monsters.config":["^[0-9]+/1/[0-9]+/(0|(1/)?name)$"],
  "hatadjectives.config":["^[0-9]+/1/[0-9]+/(0|(1/)?name)$"],
  "cockpit.config": ["^systemTooltipConfig/type/.+$", "^systemTooltipConfig/explored/.+$", "^visitableTypeDescription/.+$"],
  "statuses.config":["^statuses/.+$"],
  "help.config": ["^[a-z]+Commands/.+$"],
  "hunger.config": ["^.*$"],
  "locations.config": [".*/name$"],
  "quests.config": ["^pronouns/.+$", "^objectiveDescriptions/.+"],
  ".species": ["^charGenTextLabels/[0-9]+$"],
  ".sbvn": ["^.+/options/[0-9]+/0$"],
  ".tech": [],
  ".cinematic": [],
  ".currency": [],
  ".liquid": [],
  ".biome": [],
  ".item": [],
  ".instrument": [],
  ".legs": [],
  ".chest": [],
  ".back": [],
  ".head": [],
  ".harvestingtool": [],
  ".flashlight": [],
  ".painttool": [],
  ".wiretool": [],
  ".tillingtool": [],
  ".miningtool": [],
  ".beamaxe": [],
  ".inspectiontool": ["^outOfRangeText/.+$", "^nothingThereText/.+$"],
  ".thrownitem": [],
  ".unlock": ["^unlockMessage$"],
  ".matitem": [],
  ".liqitem": [],
  ".augment": [],
  ".consumable": [],
  ".coinitem": [],
  ".activeitem": [ "^altAbility/name$"],
  ".particle": [],
  ".damage": [],
  ".statuseffect": [],
  ".stagehand": ["^radioMessages/[^/]+/(0|2)$"],
  ".material": [],
  ".matmod": [],
  ".npctype": ["^scriptConfig/crew/role/(name|field)$", "^scriptConfig/crew/ranks/[0-9]+$", "^npcname$", "^scriptConfig/behaviorConfig/(bribeTitle|bribeSubtitle|bribeHatMessage|bribeMessage|bribeOk|bribeCancel)$" ],
  ".mat": [],
  "bounty.config": [],
  ".radiomessages": [],
  ".bush": [],
  ".grass": [],
  ".monstertype": ["^(.+/)?dialog/.+$"],
  ".monsterskill": ["^label$"],
  ".aimission": [".*Text$"],
  ".questtemplate": ["^.+Text(/[^0-9]+([0-9]+/1)?/[0-9]+)?$",
    "^scriptConfig/(descriptions|.+Note|parcel(Name|Description))/.+$",
      "^.+/example/name$", "^scriptConfig/objectiveLists/[^/]+/[0-9]+/0$", "^scriptConfig/rankTitles/[a-zA-Z]", "^scriptConfig/rankText/[a-zA-Z]"],
  ".tooltip": [],
  ".itemdescription": [],
  ".weaponability": ["^ability/name$"],
  ".collection": ["^title$"],
  "player.config": ["^collectableUnlock$"],
  "placestation.config": ["^nameLabel$", "^descriptionLabel$"],
  "techupgradegui.config": ["^slotLabelText/Head$", "^slotLabelText/Body$", "^slotLabelText/Legs$"],
  "teleportdialog.config": ["^beamPartyMemberLabel$", "^deployPartyMemberLabel$"],
  "chieftain.behavior": ["root/children/4/parameters/content/[a-zA-Z]"],
  "gang.config": [],
  "clue_items.config": ["^audiodisc/diversion$"],
  "bounty.config": [],
  "bountyassignment.questtemplate": [],
  "_metadata":[]

  }
files_of_interest = dict()
for ext, poi in foi.items():
  files_of_interest[ext] = list()
  for p in poi:
    #print(p)
    files_of_interest[ext].append(regex(p))
